### ISSUE TITLE
Facebook OAuth 2.12

### ISSUE THREAD

**Issue by guyellis** [rwky/passport-facebook#1]
Thanks @rwky for publishing this updated version of `passport-facebook`!

Since you published it I think that Facebook has updated a couple more times. Could you see what the effort would be to bump this to 2.12? Thanks.

**Comment by rwky** [comment]
I've pushed version 2.3.0 to NPM which uses v2.12

**Comment by guyellis** [comment]
I didn't even realize that the option for version had been added otherwise I wouldn't have created this.

Thanks for making `2.12` the default!

**Comment by rwky** [comment]
No worries, that option is only available in my npm repo it hasn't been merged in upstream yet sadly :(

**Comment by rwky** [comment]
FYI 2.3.0 was broken I've pushed 2.3.1 to npm which works.

**Comment by rwky** [comment]
@guyellis this has been forked into https://github.com/passport-next/passport-facebook if you're interested in becoming a contributor let me know in that repo.
